### PR TITLE
Adding a loading prop

### PR DESCRIPTION
**Pull request by sonaye**
A small edit, now we can pass a loading prop that renders an element while loading the image.

e.g.

``` javascript
const full = { flex: 1 };
const landing = { flex: 1, alignItems: 'center', justifyContent: 'center' };

<FadeIn loading={() => <View style={landing}><ActivityIndicator /></View>} style={full}>
  <Image source={{ uri: 'https://foo' }} style={full} />
</FadeIn>
```

### CODE REVIEW

**Comment by sonaye** [comment]
@brentvatne

**Comment by brentvatne** [comment]
@sonaye - can we call this `renderPlaceholder` instead?

**Comment by sonaye** [comment]
@brentvatne sure, `renderPlaceholder` sound good to me, i no longer have editing privileges though, it seems that i have deleted the fork, i submitted this a while ago.

The edit is very minor, instead of `this.props.loading` we go with `this.props.renderPlaceholder` in `FadeIn.(ios/android).js`.

**Comment by cyprusglobe** [comment]
@sonaye if you want i can redo this PR for you

**Comment by brentvatne** [comment]
@cyprusglobe - that would be great!

**Comment by sonaye** [comment]
@cyprusglobe i'll take care of it

**Pull request closed without merging**
